### PR TITLE
Final

### PR DESCRIPTION
**Pull request by elmar8287**
- Add a Navigation bar.
- Add three content sections:

1. Books list.
2. Add book form.
3. Contact info.

- Display the current date below the navigation bar.

### CODE REVIEW

**Review by abruzy — APPROVED** [review]
```markdown
Hi @erezfree29 & @andersonlebon 👋🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

[OPTIONAL]

you can consider:
- clearing the input field after adding a book
- you can want to add `cursor: pointer` to the links in the navbar to show that they are links and this will also improve the user experience of your app.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by elmar8287** [comment]
Hi @abruzy,

I have not approved it on my dashboard. Could you check it?

My regards,

Elmar

**Review by Dipeshtwis — APPROVED** [review]
# Status: Approved ✔️

## Hi @elmar8287, @andersonlebon &  @erezfree29 . 

### Sorry for the mistake happened by the previous reviewer, it's just by mistake and not by any intention. :slightly_smiling_face: 

Good job on implementing all the requirements. Well Done.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
_**Dipesh Kumar**_

--------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by elmar8287** [comment]
Dear @Dipeshtwis! 🥇 

Many thanks for the review. I appriciate your comments 👍 

Many thanks and regards,

Elmar

**Pull request merged**
